"""Add Product Brand FK

Revision ID: 13506e8bb6a5
Revises: 6d0b85114016
Create Date: 2024-11-14 21:59:15.066338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13506e8bb6a5'
down_revision: Union[str, None] = '6d0b85114016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('slug', sa.String(length=50), nullable=False))
    op.add_column('products', sa.Column('product_brand_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(op.f('uq_products_slug'), 'products', ['slug'])
    op.create_foreign_key(op.f('fk_products_product_brand_id_brands'), 'products', 'brands', ['product_brand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_products_product_brand_id_brands'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('uq_products_slug'), 'products', type_='unique')
    op.drop_column('products', 'product_brand_id')
    op.drop_column('products', 'slug')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
