"""init2

Revision ID: a5fb8bba63c2
Revises: 
Create Date: 2024-11-20 20:50:30.397104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_storages
from app.src.models.product import storage



from typing import Any






# revision identifiers, used by Alembic.
revision: str = 'a5fb8bba63c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('name', name=op.f('uq_brands_name'))
    )
    op.create_table('sizes',
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sizes')),
    sa.UniqueConstraint('size', name=op.f('uq_sizes_size'))
    )
    op.create_table('products',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('image', fastapi_storages.integrations.sqlalchemy.FileType(storage), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gendertype'), nullable=False),
    sa.Column('product_size_id', sa.UUID(), nullable=True),
    sa.Column('product_brand_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_brand_id'], ['brands.id'], name=op.f('fk_products_product_brand_id_brands')),
    sa.ForeignKeyConstraint(['product_size_id'], ['sizes.id'], name=op.f('fk_products_product_size_id_sizes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('name', name=op.f('uq_products_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_products_slug'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('sizes')
    op.drop_table('brands')
    # ### end Alembic commands ###
