"""Add Brand Add Size

Revision ID: 84ec2f0ac066
Revises: e058315bb950
Create Date: 2024-11-13 15:20:27.342831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ec2f0ac066'
down_revision: Union[str, None] = 'e058315bb950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('Brand name', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('Brand name', name=op.f('uq_brands_Brand name'))
    )
    op.create_table('sizes',
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sizes')),
    sa.UniqueConstraint('size', name=op.f('uq_sizes_size'))
    )
    op.create_unique_constraint(op.f('uq_products_name'), 'products', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_products_name'), 'products', type_='unique')
    op.drop_table('sizes')
    op.drop_table('brands')
    # ### end Alembic commands ###
