"""Add Active Field for Product

Revision ID: 21fd6991fe8c
Revises: a5fb8bba63c2
Create Date: 2024-11-21 13:56:03.936140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_storages
from app.src.models.product import storage



from typing import Any






# revision identifiers, used by Alembic.
revision: str = '21fd6991fe8c'
down_revision: Union[str, None] = 'a5fb8bba63c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_active')
    # ### end Alembic commands ###
